### ISSUE TITLE
Tokenization / Lexer

### ISSUE THREAD

**Issue by FernandaMatt** [michaelrodriguess/mini-bash#26]
## Todo

- [x] Palavra **(0)**
- [x] Pipe `|` **(1)**
- [x] Redirect `>` **(2)**
- [x] Redirect `<` **(3)**
- [x] Redirect `>>` **(4)**
- [x] Redirect `<<` **(5)**
- [x] Aspas duplas `"` **(6)**
- [x] Aspas simples `'` **(7)**

cat Makefile |.      wc    -l.     >>   "     temp.txt    '      "
(0)    (0).      (1)   (0).  (0)    (2)  (3)      (0)        (4)   (3)
 
0 -> word
1 -> pipe
2 -> redirect

### Work in Progress

**Example**
```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct Token {
  int type;
  char *word;
  struct Token *next;
};

struct Token *lexer(const char *input) {
  struct Token *head = NULL;
  struct Token *current = NULL;

  int len = strlen(input);
  int i = 0;
  while (i < len) {
    int type = 0;
    int start = i;
    int end = i;

    if (input[i] == '|') {
      type = 1;
      end = ++i;
    } else if (input[i] == '>' || input[i] == '<') {
      type = 2;
      end = ++i;
    } else if (input[i] == '\"' || input[i] == '\'') {
      type = 3;
      start = ++i;
      char quote = input[start - 1];
      while (i < len && input[i] != quote) {
        i++;
      }
      end = i;
      if (i < len) {
        i++;
      }
    } else {
      while (i < len && input[i] != '|' && input[i] != '>' && input[i] != '<' && input[i] != '\"' && input[i] != '\'') {
        i++;
      }
      end = i;
    }

    struct Token *token = (struct Token *)malloc(sizeof(struct Token));
    token->type = type;
    token->word = (char *)malloc(end - start + 1);
    memcpy(token->word, input + start, end - start);
    token->word[end - start] = '\0';
    token->next = NULL;

    if (head == NULL) {
      head = token;
    } else {
      current->next = token;
    }
    current = token;
  }

  return head;
}

void print_tokens(const struct Token *head) {
  while (head != NULL) {
    printf("Type: %d, Word: %s\n", head->type, head->word);
    head = head->next;
  }
}

int main() {
  const char *input = "ls -l | grep \"hello world\" > output.txt";
  struct Token *head = lexer(input);
  print_tokens(head);
  return 0;
}
```

---

### Work in Progress

A função tokenize recebe como entrada uma string e retorna uma lista de tokens, onde cada token tem um tipo (palavra, pipe, redirecionamento ou aspas) e um valor (o conteúdo da palavra, pipe, redirecionamento ou aspas). 

Este código é um exemplo de um lexer simples escrito em C, que lê uma sequência de entrada de caracteres e produz uma lista de tokens com informações sobre o tipo e a palavra correspondente a cada token.

O processo de criação do código envolve a definição de uma estrutura de dados de token, a implementação de uma função de lexer para analisar a entrada de caracteres e gerar os tokens correspondentes, e uma função de impressão de tokens para exibir os resultados na saída.

A função de lexer usa um loop para percorrer a entrada de caracteres, identificar o tipo de cada token com base em regras simples (como caracteres especiais ou aspas), criar um novo token para cada sequência de caracteres que corresponde a um token, e encadear os tokens na lista de tokens.

A função de impressão de tokens apenas percorre a lista de tokens e imprime as informações de tipo e palavra para cada token na saída.

**Comment by FernandaMatt** [comment]
### Funcionalidades dos caracteres especiais

* single quote ' and double quotes "

From the bash manual:
[3.1.2.2 Single Quotes](http://www.gnu.org/software/bash/manual/html_node/Single-Quotes.html)
Enclosing characters in single quotes (') preserves the literal value of each character within the quotes. A single quote may not occur between single quotes, even when preceded by a backslash.
[3.1.2.3 Double Quotes](http://www.gnu.org/software/bash/manual/html_node/Double-Quotes.html)
Enclosing characters in double quotes (") preserves the literal value of all characters within the quotes, with the exception of $, `, \, and, when history expansion is enabled, !. The characters $ and ` retain their special meaning within double quotes (see [Shell Expansions](https://www.gnu.org/software/bash/manual/html_node/Shell-Expansions.html#Shell-Expansions)). The backslash retains its special meaning only when followed by one of the following characters: $, `, ", \, or newline. Within double quotes, backslashes that are followed by one of these characters are removed. Backslashes preceding characters without a special meaning are left unmodified. A double quote may be quoted within double quotes by preceding it with a backslash. If enabled, history expansion will be performed unless an ! appearing in double quotes is escaped using a backslash. The backslash preceding the ! is not removed.

**Comment by michaelrodriguess** [comment]
ola
