### ISSUE TITLE
Allowed Functions Overview

### ISSUE THREAD

**Issue by FernandaMatt** [michaelrodriguess/mini-bash#5]
| **N** | **O** | **T** | **E** |
| -------------------- | ---------------------- | ---------------------- | ---------------------- |
| <li>- [ ] [readline ](https://github.com/michaelrodriguess/mini-bash/issues/5#issuecomment-1430512754)| <li>- [ ] rl_clear_history </li> | <li>- [ ] rl_on_new_line </li> | <li>- [ ] rl_replace_line </li> |
| <li>- [ ] rl_redisplay </li> | <li>- [ ] [add_history](https://github.com/michaelrodriguess/mini-bash/issues/5#issuecomment-1452249200) </li> |<li>- [ ] printf </li> | <li>- [ ] malloc </li> |
| <li>- [ ] free </li> | <li>- [ ] write </li> | <li>- [ ] access </li> | <li>- [ ] open </li> |
| <li>- [ ] read </li> | <li>- [ ] close </li> | <li>- [ ] [fork ](https://github.com/michaelrodriguess/mini-bash/issues/5#issuecomment-1453720279)</li> | <li>- [ ] wait </li> |
| <li>- [ ] waitpid </li> | <li>- [ ] wait3 </li> | <li>- [ ] wait4 </li> | <li>- [ ] signal </li> |
| <li>- [ ] sigaction </li> | <li>- [ ] sigemptyset </li> | <li>- [ ] sigaddset </li> | <li>- [ ] kill </li> |
| <li>- [ ] exit </li> | <li>- [ ] [getcwd](https://github.com/michaelrodriguess/mini-bash/issues/5#issuecomment-1430512754) </li> | <li>- [ ] [chdir ](https://github.com/michaelrodriguess/mini-bash/issues/5#issuecomment-1453694278)</li> | <li>- [ ] stat </li> |
| <li>- [ ] lstat </li> | <li>- [ ] fstat </li> | <li>- [ ] unlink </li> | <li>- [ ] [execve](https://github.com/michaelrodriguess/mini-bash/issues/5#issuecomment-1453720279) </li> |
| <li>- [ ] dup </li> | <li>- [ ] dup2 </li> | <li>- [ ] pipe </li> | <li>- [ ] opendir </li> |
| <li>- [ ] readdir </li> | <li>- [ ] closedir </li> | <li>- [ ] strerror </li> | <li>- [ ] perror </li> |
| <li>- [ ] isatty </li> | <li>- [ ] ttyname </li> | <li>- [ ] ttyslot </li> | <li>- [ ] ioctl </li> |
| <li>- [ ] getenv </li> | <li>- [ ] tcsetattr </li> | <li>- [ ] tcgetattr </li> | <li>- [ ] tgetent </li> |
| <li>- [ ] tgetflag </li> | <li>- [ ] tgetnum </li> | <li>- [ ] tgetstr </li> | <li>- [ ] tgoto </li> |
| <li>- [ ] tputs </li> |  | |

**Comment by FernandaMatt** [comment]
* ### Readline

The readline function will read a line from the terminal and return it. The string returned will be allocated with malloc (it must be freed by the user). The declaration for readline is:

`char *readline (char *prompt)`

char *prompt -> string displayed on the terminal while waiting for the line input.


The readline library also has functions to maintain a list of previously-entered command lines and deal with that history. During the build process the readline and history libraries where placed into separate libraries, allowing the history functions to be used without readline.

The readline library also offers editing capabilities while the user is entering the line. This allow auto-completion features, like the functionality of TAB ⭾ when completing the name of a file.

This is the library used to implement bash.

🇧🇷

A funcao readline irá ler uma linha do terminal e retorná-la como uma string mallocada (essa string deve ser depois liberada pelo usuário com uso da funcao free). A declaracao da funcao readline é:

`char *readline (char *prompt)`

char *prompt -> string exibida no terminal enquanto espera pelo input do usuário.

A biblioteca readline também tem funcoes para manter e utilizar um histórico das ultimas linhas de comando retornadas. Durante o processo de construcao da biblioteca as funcoes de manipulacao de histórico foram separadas em uma bilbioteca a parte para utilizacao em projetos sem a necessidade da biblioteca readline.

A biblioteca readline ainda oferece a possibilidade de edicao da linha de comando enquanto a mesma esta sendo inserida pelo usuario, permitindo, por exemplo, o funcionamento de "auto-completacao" (por exemplo ao dar TAB ⭾ e completar o nome de um arquivo).

Essa é a mesma biblioteca usada para implementacao do bash.

**Comment by FernandaMatt** [comment]
* ### getcwd

**Comment by michaelrodriguess** [comment]
🇧🇷

***add_history*** → A função `add_history()` em C é uma função que adiciona uma entrada ao histórico de comandos executados em um programa de linha de comando, como um interpretador de comandos ou um shell.

&ensp;O histórico de comandos é uma lista de comandos que foram digitados e executados anteriormente pelo usuário. Ele permite que o usuário acesse rapidamente comandos anteriores e evita que o usuário precise digitar comandos repetitivos várias vezes.
&ensp;A função add_history() é definida na biblioteca "readline" em C e é usada para adicionar uma linha de comando ao histórico. A sintaxe da função é a seguinte:

```c
void add_history(const char *line);
```
&ensp;A função recebe uma string `line` que representa o comando a ser adicionado ao histórico. Podemos usar a funcao add_history(3) para pegar os histórico da linha comando.

***rl_clear_history*** → A função `rl_clear_history()` faz parte da biblioteca `readline` em C e é usada para limpar o histórico de comandos de entrada que é mantido pela biblioteca. O histórico de comandos mantém um registro dos comandos digitados pelo usuário em uma aplicação interativa de linha de comando e permite que eles sejam recuperados e reutilizados posteriormente.
&ensp;A chamada da função `rl_clear_history()` remove todos os comandos anteriores armazenados no histórico da biblioteca `readline`, deixando-o vazio. O uso da função `rl_clear_history()` pode ser útil em vários cenários, incluindo:

- Em uma aplicação interativa de linha de comando que lida com informações confidenciais, como senhas ou informações financeiras, a chamada da função `rl_clear_history()` pode ser usada para garantir que os comandos de entrada anteriores não sejam mais acessíveis após o término da sessão.
- Quando uma aplicação interativa de linha de comando é encerrada, a chamada da função `rl_clear_history()` pode ser usada para limpar o histórico de comandos armazenados em memória, liberando espaço e evitando vazamentos de memória.

   A função `rl_clear_history()` é uma das várias funções disponíveis na biblioteca `readline` em C que ajudam a gerenciar o histórico de comandos de entrada. Outras funções incluem `add_history()`, que adiciona um novo comando ao histórico, `history_list()`, que lista os comandos no histórico, e `history_get()`, que recupera um comando específico do histórico com base em seu índice.

🇺🇸 

***add_history*** → The `add_history()` function in C is a function that adds an entry to the history of commands executed in a command line program, such as a command interpreter or shell.

&ensp;The command history is a list of commands that have been typed and executed previously by the user. It allows the user to quickly access previous commands and saves the user from having to type repetitive commands over and over again.
&ensp;The add_history() function is defined in the C library "readline" and is used to add a command line to the history. The syntax of the function is as follows:

```c
void add_history(const char *line);
```
&ensp;The function takes a string `line` that represents the command to add to the history. We can use add_history(3) to get the history from the command line.

***rl_clear_history*** → The `rl_clear_history()` function is part of the `readline` library in C and is used to clear the history of incoming commands that is kept by the library. The command history keeps a record of the commands entered by the user in an interactive command-line application and allows them to be retrieved and reused later.
&ensp;Calling the `rl_clear_history()` function removes all previous commands stored in the library `readline` history, leaving it empty. Using the `rl_clear_history()` function can be useful in several scenarios, including:

- In an interactive command-line application that handles sensitive information, such as passwords or financial information, calling the `rl_clear_history()` function can be used to ensure that previous input commands are no longer accessible after the session ends.
- When an interactive command line application is terminated, the `rl_clear_history()` function call can be used to clear the history of commands stored in memory, freeing up space and preventing memory leaks.

   The `rl_clear_history()` function is one of several functions available in the C `readline` library that help manage the history of incoming commands. Other functions include `add_history()`, which adds a new command to the history, `history_list()`, which lists the commands in the history, and `history_get()`, which retrieves a specific command from the history based on its index.

**Comment by michaelrodriguess** [comment]
🇧🇷

***ioctl*** → O `ioctl` é uma chamada de sistema em C que é usada para controlar dispositivos ou modificar o comportamento do sistema operacional.
&ensp;O `ioctl` é usado para enviar comandos específicos de dispositivos para drivers de dispositivo. Ele permite que os programas interajam com dispositivos de hardware, como discos, dispositivos USB, placas de som, entre outros. Por exemplo, ele pode ser usado para definir a velocidade de transmissão de um modem ou para definir a resolução de uma tela.

A sintaxe do `ioctl` é a seguinte:

```c
int ioctl(int fd, unsigned long request, ...);
```

&ensp;O primeiro parâmetro, `fd`, é o descritor de arquivo do dispositivo com o qual você deseja interagir. O segundo parâmetro, `request`, é um código que identifica o comando que você deseja enviar para o dispositivo. O terceiro parâmetro é um argumento opcional que é usado para passar informações adicionais para o comando.

    O `request` é um código que é específico para cada driver de dispositivo e é definido pelo desenvolvedor do driver. O `ioctl` é geralmente usado em conjunto com uma estrutura de dados que é passada como parâmetro, e esta estrutura é específica para o comando `request` enviado.

    No geral, o `ioctl` é uma chamada de sistema poderosa que permite que os programas controlem dispositivos e personalizem o comportamento do sistema operacional. No entanto, deve ser usado com cuidado, pois o uso indevido pode causar problemas de segurança e estabilidade do sistema.

&ensp;&ensp;***TIOCSTI*** → A macro `TIOCSTI` é uma das muitas macros disponíveis na biblioteca `ioctl` em C. Essa macro é usada para inserir um único caractere na entrada de um terminal. Quando a macro `TIOCSTI` é chamada, ela envia o caractere 
especificado para a fila de entrada do terminal. Isso faz com que o caractere seja tratado como se fosse digitado pelo usuário no teclado.

🇺🇸

***ioctl*** → The `ioctl` is a C system call that is used to control devices or modify operating system behavior.
&ensp;The `ioctl` is used to send device-specific commands to device drivers. It allows programs to interact with hardware devices such as disks, USB devices, sound cards, and so on. For example, it can be used to set the baud rate of a modem or to set the resolution of a screen.

The syntax of `ioctl` is as follows:

```c
int ioctl(int fd, unsigned long request, ...);
```

&ensp;The first parameter, `fd`, is the file descriptor of the device you wish to interact with. The second parameter, `request`, is a code that identifies the command you want to send to the device. The third parameter is an optional argument that is used to pass additional information to the command.

    The `request` is a code that is specific to each device driver and is defined by the driver developer. The `ioctl` is usually used in conjunction with a data structure that is passed as a parameter, and this structure is specific to the `request` command being sent.

    Overall, `ioctl` is a powerful system call that allows programs to control devices and customize the behavior of the operating system. However, it should be used with care, as misuse can cause security and system stability problems.

&ensp;&ensp;***TIOCSTI*** → The `TIOCSTI` macro is one of the many macros available in the C library `ioctl`. This macro is used to insert a single character into the input of a terminal. When the `TIOCSTI` macro is called, it sends the specified 
character to the input queue of the terminal. This causes the character to be treated as if it were typed by the user at the keyboard.

**Comment by michaelrodriguess** [comment]
🇧🇷

&nbsp;&nbsp;Em C, sinais (também conhecidos como "signals" em inglês) são eventos assíncronos que podem ser enviados para um processo por outro processo ou pelo sistema operacional. Os sinais podem ser usados para notificar um processo sobre eventos externos, como a chegada de dados de entrada ou a conclusão de uma tarefa.

&nbsp;&nbsp;O mecanismo de sinais em C funciona da seguinte forma: quando um processo recebe um sinal, ele interrompe sua execução atual e trata o sinal. O tratamento do sinal pode ser uma ação predefinida ou personalizada, como fechar o processo ou salvar seu estado atual antes de continuar a execução. Depois que o tratamento do sinal é concluído, o processo retorna à sua execução normal.

&nbsp;&nbsp;Os sinais em C são identificados por números inteiros, como SIGINT (geralmente enviado pelo usuário através da combinação de teclas Ctrl + C), SIGTERM (usado para solicitar a finalização de um processo) e SIGKILL (usado para encerrar abruptamente um processo). Para tratar sinais em C, é possível usar a função "signal()", que permite definir uma função para lidar com um sinal específico.

&nbsp;&nbsp;No entanto, a manipulação de sinais em C pode ser complexa e deve ser realizada com cuidado para evitar comportamentos indesejados ou bugs no código. É importante entender a natureza assíncrona dos sinais e considerar os efeitos que eles podem ter em outros processos ou no sistema como um todo.

Há vários comportamentos indesejados que podem ocorrer se a manipulação de sinais em C não for feita corretamente, como:

1. Sinais perdidos: Se um processo estiver executando uma tarefa crítica e receber um sinal, pode ser interrompido e perder o sinal se a manipulação do sinal não for feita de forma adequada. Isso pode causar comportamentos imprevisíveis e potencialmente perigosos.
2. Concorrência: Se vários sinais forem recebidos simultaneamente, pode haver conflitos de concorrência que causem falhas no programa ou comportamentos inesperados.
3. Manipulação inapropriada: Se o tratamento de sinal não for feito corretamente, o programa pode se comportar de forma inesperada ou até mesmo travar. Por exemplo, um programa pode não ter um tratamento adequado para um determinado sinal, o que pode resultar em uma finalização inesperada ou em um loop infinito.
4. Race conditions: Se o código de tratamento de sinal compartilha recursos críticos com o código principal do programa, pode ocorrer uma condição de corrida (race condition), na qual a execução do programa pode ser afetada por mudanças imprevisíveis nos recursos compartilhados.
5. Segurança: Se um programa não estiver preparado para lidar com sinais externos, ele pode estar vulnerável a ataques de negação de serviço (DoS), em que um invasor envia sinais repetidos para o programa para sobrecarregá-lo ou causar sua interrupção.

Por isso, é importante que a manipulação de sinais em C seja feita com cuidado e atenção aos detalhes, para evitar esses e outros comportamentos indesejados que possam afetar a execução do programa ou até mesmo comprometer sua segurança.

🇺🇸


&nbsp;&nbsp;In C, signals are asynchronous events that can be sent to a process by another process or by the operating system. Signals can be used to notify a process of external events, such as the arrival of input data or the completion of a task.

&nbsp;&nbsp;The C signal mechanism works as follows: when a process receives a signal, it stops its current execution and handles the signal. The signal handling can be a predefined or custom action, such as closing the process or saving its current state before continuing execution. After the signal handling is complete, the process returns to its normal execution.

C signals are identified by integers, such as SIGINT (usually sent by the user with the key combination Ctrl + C), SIGTERM (used to request the termination of a process) and SIGKILL (used to abruptly terminate a process). To handle signals in C you can use the "signal()" function, which allows you to define a function to handle a specific signal.

However, signal handling in C can be complex and must be done carefully to avoid unwanted behavior or bugs in the code. It is important to understand the asynchronous nature of signals and consider the effects they may have on other processes or the system as a whole.

There are several unwanted behaviors that can occur if signal manipulation in C is not done correctly, such as:

1. Missed signals: If a process is performing a critical task and receives a signal, it can be interrupted and lose the signal if the signal is not handled properly. This can cause unpredictable and potentially dangerous behavior.
2. Concurrency: If multiple signals are received simultaneously, there can be concurrency conflicts that cause program crashes or unexpected behavior.
3. Improper handling: If the signal handling is not done correctly, the program may behave unexpectedly or even crash. For example, a program may not have proper handling for a particular signal, which may result in unexpected termination or an infinite loop.
4. Race conditions: If the signal-handling code shares critical resources with the main program code, a race condition can occur, in which program execution can be affected by unpredictable changes in the shared resources.
5. Security: If a program is not prepared to handle external signals, it may be vulnerable to denial of service (DoS) attacks, in which an attacker sends repeated signals to the program to overload it or cause it to stop.

It is therefore important that the manipulation of signals in C is done with care and attention to detail to avoid these and other unwanted behaviors that can affect the execution of the program or even compromise its security.

**Comment by FernandaMatt** [comment]
***chdir()*** →

**Comment by FernandaMatt** [comment]
🇺🇸

***execve()*** → The `execve()` function
